apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: go-hsgyxtax 
  janus-idp.io/tekton: go-hsgyxtax
  backstage.io/kubernetes-id: go-hsgyxtax
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: go-hsgyxtax
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml