apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-hsgyxtax
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-hsgyxtax:78b23a52f1285462d93d55acacdd93bbe60f4914@sha256:ab9f7aa91a9332547c1e0337bdc9d9a33390ed8d4364ab045435fd89e1e271a8
        name: container-image  
